import { sampleSettings } from "../data.js";
import { badge, esc, icon, money, pageHeading, panel } from "../components.js";

const categoryTabs = ["Tổng quan", "Marketplace", "In 3D"];

export function renderSettings(state) {
  const settings = { ...sampleSettings, ...(state.settings || {}) };
  const checked = settings.requireProductReview ? "true" : "false";
  const chips = (name, values) => `<div class="tag-row settings-tags">${values.map(value => `<span class="tag">${esc(value)}<button type="button" data-action="remove-setting-tag" data-tag-group="${name}" data-tag="${esc(value)}" aria-label="Xóa ${esc(value)}">×</button></span>`).join("")}<button type="button" class="tag add-tag" data-action="add-setting-tag" data-tag-group="${name}">${icon("plus")} Thêm</button></div>`;
  const general = `<section class="setting-group" id="settings-general"><h3>Tổng quan</h3><p>Thông tin hiển thị mặc định cho khu vực quản trị marketplace.</p><div class="form-grid"><label class="form-field">Tên nền tảng<input name="platformName" value="${esc(settings.platformName)}" required></label><label class="form-field">Đơn vị tiền tệ<select name="currency"><option ${settings.currency.startsWith("VND") ? "selected" : ""}>VND · Việt Nam Đồng</option><option>USD · US Dollar</option></select></label><label class="form-field wide">Múi giờ<select name="timezone"><option ${settings.timezone.includes("Ho_Chi_Minh") ? "selected" : ""}>Asia/Ho_Chi_Minh (UTC+7)</option><option>Asia/Bangkok (UTC+7)</option></select></label></div></section>`;
  const market = `<section class="setting-group" id="settings-marketplace"><h3>Marketplace</h3><p>Các giá trị demo có thể điều chỉnh tại local state; chưa áp dụng lên giao dịch thật.</p><div class="form-grid"><label class="form-field">Commission mặc định (%)<input name="commissionRate" type="number" min="0" max="100" step="0.5" value="${esc(settings.commissionRate ?? state.commissionRate ?? 10)}"></label><label class="form-field">Tiền cọc tham khảo<input name="requiredDeposit" type="number" min="0" step="500000" value="${esc(settings.requiredDeposit)}"></label></div><div class="toggle-row"><span class="toggle-copy"><strong>Yêu cầu Admin review sản phẩm</strong><small>Sản phẩm cần review trước khi public theo cấu hình demo hiện tại.</small></span><button type="button" class="switch" role="switch" aria-checked="${checked}" data-action="settings-toggle" aria-label="Bật tắt review sản phẩm"></button></div><div class="toggle-row"><span class="toggle-copy"><strong>Seller tự đăng ký hoạt động</strong><small>Không có trạng thái chờ Admin approval trong luồng seller.</small></span>${badge("Đang bật", "success")}</div></section>`;
  const printing = `<section class="setting-group" id="settings-printing"><h3>Tùy chọn in 3D</h3><p>Danh mục tham chiếu để seller khai báo năng lực và cấu hình dịch vụ.</p><label class="form-field">Công nghệ in</label>${chips("printingTechnologies", settings.printingTechnologies)}<label class="form-field setting-label">Vật liệu</label>${chips("materials", settings.materials)}<label class="form-field setting-label">Chất lượng bề mặt</label>${chips("surfaceQualities", settings.surfaceQualities)}</section>`;
  return `${pageHeading("WORKSPACE CONFIGURATION", "Cấu hình Marketplace", "Thiết lập thông tin nền tảng và các tùy chọn vận hành cho giao diện demo.", `<button class="button" form="marketplace-settings" type="submit">${icon("check")} Lưu cấu hình</button>`)}<div class="demo-strip">${icon("spark")} Thay đổi được lưu ở local state / trình duyệt này; cần backend để đồng bộ đa người dùng</div><div class="settings-nav">${categoryTabs.map((tab, index) => `<button data-settings-scroll="settings-${["general", "marketplace", "printing"][index]}">${tab}</button>`).join("")}</div>${panel("Thiết lập nền tảng", "Cấu hình UI mẫu · Có thể map sang API sau này", `<form id="marketplace-settings" data-form="settings">${general}${market}${printing}<div class="setting-footer"><span>${icon("clock")} Cập nhật cục bộ trong phiên demo</span><button class="button" type="submit">Lưu thay đổi</button></div></form>`)}`;
}
